name: Deploy to Test Heroku

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**

jobs:

  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_STG_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_STG_KEY }}
          export_default_credentials: true
      - name: set gcp credentials
        run:  gcloud info
      - name: echo gcp credentials
        run:  echo this is ${GOOGLE_APPLICATION_CREDENTIALS}

  clean:
    runs-on: ubuntu-latest
    needs: export
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run the Maven Package Phase
        run: mvn --batch-mode --update-snapshots verify

  build:
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Deploy, Push to heroku
        id: heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3 #action to build a
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "golfwithmeservice-test" #Must be unique in Heroku
          email: "stanfa.michael@gmail.com"
          process_type: web