name: Deploy to Test Heroku

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Deploy, Push to heroku
        id: heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3 #action to build a
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "golfwithmeservice-test" #Must be unique in Heroku
          email: "stanfa.michael@gmail.com"