name: Deploy to Test Heroku

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run the Maven Package Phase
        run: mvn --batch-mode --update-snapshots verify

  build:
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Deploy, Push to heroku
        id: heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3 #action to build a
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "golfwithmeservice-test" #Must be unique in Heroku
          email: "stanfa.michael@gmail.com"
          process_type: web