name: Deploy to Test Heroku

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Deploy, Push to heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3 #action to build a
#        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "golfwithmeservice-test" #Must be unique in Heroku
          email: "stanfa.michael@gmail.com"
          dockerfile_path: /
